### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [luissilva1044894/Pyrez#115]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 1.1.0.3. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary pyrez -w /tmp/ext pyrez==1.1.0.3
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting pyrez==1.1.0.3
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/3dc/4af230bf8eb34/pyrez-1.1.0.3.tar.gz (58 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ca8216zs/pyrez/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ca8216zs/pyrez/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ca8216zs/pyrez/pip-egg-info
         cwd: /tmp/pip-wheel-ca8216zs/pyrez/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ca8216zs/pyrez/setup.py", line 215, in <module>
        'dev': __getRequirements('dev'),
      File "/tmp/pip-wheel-ca8216zs/pyrez/setup.py", line 46, in __getRequirements
        for requirement in __readFile('requirements/{}'.format(fileName if fileName.endswith(".txt") else '{}.txt'.format(fileName))).splitlines():
      File "/tmp/pip-wheel-ca8216zs/pyrez/setup.py", line 37, in __readFile
        with open(os.path.join(HERE, fileName), 'r', encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-wheel-ca8216zs/pyrez/requirements/dev.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by luissilva1044894** [comment]
Yo, @thatch! Would you possibly submit a Pull Request?

**Comment by thatch** [comment]
Yes, but I have to script it first :)

**Comment by luissilva1044894** [comment]
It was something about using `requeriments` folder and not adding it on `MANIFEST.in`, I guess? 

Also, why do you need `no-binary`?

**Comment by thatch** [comment]
Some companies and distros want to compile everything from source, so pass `--no-binary :all:`, for example https://github.com/dropbox/dbx_build_tools/blob/master/build_tools/py/vpip.py#L311

**Comment by luissilva1044894** [comment]
Thanks! ❤️
