### ISSUE TITLE
getMatchHistory

### ISSUE THREAD

**Issue by iforvard** [luissilva1044894/Pyrez#13]
https://github.com/luissilva1044894/Pyrez/blob/4d1d44c9c77bd88dac83a02c2d5cfe1f9a745852/pyrez/models.py#L443

Here is such a mistake.
But there is a delete int everything works

C:\Users\IP\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/IP/PycharmProjects/SmiteChek/main.py
Traceback (most recent call last):
  File "C:/Users/IP/PycharmProjects/SmiteChek/main.py", line 5, in <module>
    r = smiteAPI.getMatchHistory(int(9236315))
  File "c:\users\ip\pycharmprojects\smitechek\src\pyrez\pyrez\api.py", line 331, in getMatchHistory
    matchHistorys.append(MatchHistory(**matchHistory))
  File "c:\users\ip\pycharmprojects\smitechek\src\pyrez\pyrez\models.py", line 443, in __init__
    self.godId = Champions(int(kwargs.get("ChampionId")))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by luissilva1044894** [comment]
@iforvard Thanks for report! Should be fixed now.
