### ISSUE TITLE
getLatestPatchNotes() is not work

### ISSUE THREAD

**Issue by cow03haha** [luissilva1044894/Pyrez#220]
getLatestPatchNotes is not work, I am not sure if I am using this method correctly
here is my code
```py
from pyrez.api import PaladinsAPI, StatusPageAPI
from pyrez.enumerations.Language import Language

paladins = PaladinsAPI(devId = 'devId', authKey = 'authKey')
data = paladins.getLatestPatchNotes()
print(data)
paladins.close()
```
and here is error
```
$ /usr/bin/python3 /media/cow03/NoobCow_CodeSpace/python/misc/paladins_api.py
Traceback (most recent call last):
  File "/media/cow03/NoobCow_CodeSpace/python/misc/paladins_api.py", line 5, in <module>
    data = paladins.getLatestPatchNotes()
  File "/home/cow03/.local/lib/python3.7/site-packages/pyrez/api/PaladinsAPI.py", line 88, in getLatestPatchNotes
    __ = self.getWebsitePost(language=language or Language.English, slug=PaladinsWebsitePost(**_[0]).slug)
  File "/home/cow03/.local/lib/python3.7/site-packages/pyrez/api/PaladinsAPI.py", line 105, in getWebsitePost
    __ = [ PaladinsWebsitePost(**___) for ___ in (_ or []) ]
  File "/home/cow03/.local/lib/python3.7/site-packages/pyrez/api/PaladinsAPI.py", line 105, in <listcomp>
    __ = [ PaladinsWebsitePost(**___) for ___ in (_ or []) ]
TypeError: type object argument after ** must be a mapping, not str
```

**Comment by luissilva1044894** [comment]
Yo, @cow03haha. Sorry for late reply. It should be working for now. I'll push a release soon.

If you find hard to format `obj['content']` / `obj.content` (RAW HTML), I've added a new method `getUrl()`.

Note: Always returns the latest patch notes on the website, may be not playable/current.
